name: Deploy to GCP VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/gcp_key
          chmod 600 ~/.ssh/gcp_key

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/gcp_key \
          ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_HOST }} \
          './update-and-restart.sh'